import java.time.DayOfWeek
import java.time.LocalTime

class SupermarketChain(
    private val supermarkets: List<Supermarket>
) {

    /**
     * Calculates the total revenue generated by all supermarkets in the chain.
     */
    fun getTotalRevenue(): Double {
        return supermarkets.sumOf { it.getTotalRevenue() }
    }

    /**
     * Finds the supermarket with the highest total revenue.
     * Returns a formatted string with the name, ID, and revenue.
     */
    fun getSupermarketWithHighestRevenue(): String {
        val winner = supermarkets.maxByOrNull { it.getTotalRevenue() }

        return if (winner != null) {
            "${winner.name} (ID: ${winner.id}). Total Revenue: ${winner.getTotalRevenue()}"
        } else {
            "No supermarkets or sales data available."
        }
    }

    /**
     * Finds the top 5 selling products across the entire chain.
     */
    fun getTop5SellingProducts(): String {
        return supermarkets
            // 1. Flatten: List<Supermarket> -> List<StockEntry>
            .flatMap { it.getSoldEntries() }
            // 2. Group: Map<Product, List<StockEntry>>
            .groupBy { it.product }
            // 3. Aggregate: Map<Product, Int (TotalQuantity)>
            .mapValues { (_, entries) -> entries.sumOf { it.soldQuantity } }
            .toList() // Convert to List<Pair<Product, Int>> to sort
            // 4. Sort & Limit
            .sortedByDescending { (_, totalQuantity) -> totalQuantity }
            .take(5)
            // 5. Format output
            .joinToString(" - ") { (product, totalQuantity) ->
                "${product.name}: $totalQuantity"
            }
    }

    /**
     * OPTIONAL OBJECTIVE:
     * Returns a list of open supermarkets given a day and time.
     */
    fun getOpenSupermarkets(day: DayOfWeek, time: LocalTime): String {
        // Pass the LocalTime object to the supermarket
        val openList = supermarkets.filter { it.isOpen(day, time) }

        if (openList.isEmpty()) {
            return "No supermarkets open at this time."
        }

        // Map to string "Name (id)" and join with commas
        return openList.joinToString(", ") { "${it.name} (${it.id})" }
    }
}