import java.time.DayOfWeek

class SupermarketChain(
    private val supermarkets: List<Supermarket>
) {

    /**
     * Calculates the total revenue generated by all supermarkets in the chain.
     */
    fun getTotalRevenue(): Double {
        return supermarkets.sumOf { it.getTotalRevenue() }
    }

    /**
     * Finds the supermarket with the highest total revenue.
     * Returns a formatted string with the name, ID, and revenue.
     */
    fun getSupermarketWithHighestRevenue(): String {
        val winner = supermarkets.maxByOrNull { it.getTotalRevenue() }

        return if (winner != null) {
            "${winner.name} (ID: ${winner.id}). Total Revenue: ${winner.getTotalRevenue()}"
        } else {
            "No supermarkets or sales data available."
        }
    }

    /**
     * Finds the top 5 selling products across the entire chain.
     * Logic:
     * 1. Collect all sold entries from all supermarkets.
     * 2. Group them by Product (aggregating sales from different locations).
     * 3. Sum the sold quantities.
     * 4. Sort descending and take the top 5.
     */
    fun getTop5SellingProducts(): String {
        return supermarkets
            // 1. Flatten: List<Supermarket> -> List<StockEntry>
            .flatMap { it.getSoldEntries() }
            
            // 2. Group: Map<Product, List<StockEntry>>
            .groupBy { it.product }
            
            // 3. Aggregate: Map<Product, Int (TotalQuantity)>
            .mapValues { (_, entries) -> 
                entries.sumOf { it.soldQuantity } 
            }
            .toList() // Convert to List<Pair<Product, Int>> to sort
            
            // 4. Sort & Limit
            .sortedByDescending { (_, totalQuantity) -> totalQuantity }
            .take(5)
            
            // 5. Format output
            .joinToString(" - ") { (product, totalQuantity) ->
                "${product.name}: $totalQuantity"
            }
    }

    /**
     * OBJETIVO OPCIONAL:
     * Retorna lista de supermercados abiertos dado un día y horario.
     */
    fun getOpenSupermarkets(day: DayOfWeek, hour: Int): String {
        val openList = supermarkets.filter { it.isOpen(day, hour) }

        if (openList.isEmpty()) {
            return "No supermarkets open at this time."
        }

        // Mapeamos a string "Nombre (id)" y unimos con comas
        return openList.joinToString(", ") { "${it.name} (${it.id})" }
    }
}